networks:
  http_network:
    external: true

services:
  webserver:
    image: "elbromasmc/alc-ti"
    restart: unless-stopped
    environment:
      - ENV=${ENV}
      - PORT=${PORT}
      - REL=${REL}
    networks:
      - http_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=http_network"
      - "traefik.http.routers.webserver.entrypoints=websecure"
      - "traefik.http.routers.webserver.rule=Host(`${WEBSERVER_HOSTNAME}`)"
      - "traefik.http.routers.webserver.tls=true"
      - "traefik.http.routers.webserver.tls.certresolver=letsencrypt"
      - "traefik.http.routers.webserver.tls.domains[0].main=${WEBSERVER_HOSTNAME}"
      - "traefik.http.routers.webserver.tls.options=default"
      - "traefik.http.services.webserver.loadbalancer.server.port=8080"
      - "traefik.http.services.webserver.loadbalancer.server.scheme=http"
